# Generated by Django 5.1.1 on 2024-10-18 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Learning_logs', '0003_topic_ofinterest_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
