# Generated by Django 5.1.1 on 2024-10-18 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Learning_logs', '0004_entry_last_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic_ofinterest',
            name='last_modified',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
