# Generated by Django 5.1.1 on 2024-10-18 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Learning_logs', '0005_topic_ofinterest_last_modified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic_ofinterest',
            name='last_modified',
        ),
    ]
