# Generated by Django 5.1.1 on 2024-10-18 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Learning_logs', '0006_remove_topic_ofinterest_last_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='last_modified',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='EntryHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='Learning_logs.entry')),
            ],
        ),
    ]
