# Generated by Django 5.1.1 on 2024-10-18 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Learning_logs', '0007_alter_entry_last_modified_entryhistory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entryhistory',
            old_name='modified_at',
            new_name='last_modified',
        ),
    ]
