# Generated by Django 5.1.1 on 2024-10-18 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Learning_logs', '0008_rename_modified_at_entryhistory_last_modified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entryhistory',
            old_name='last_modified',
            new_name='date_created',
        ),
    ]
